AL:
  strategy: CCAL
  ood_ratio: 0.1
  nb_id_class: 4
  openset_params:
    k: 100.0
    t: 0.9
    distinctive_params:
      modelname: resnet18
      pretrained: false
      simclr_dim: 128
      shift_trans_type: rotation
      sim_lambda: 1.0
      epochs: 700
      batch_size: 32
      num_workers: 8
      opt_name: SGD
      lr: 0.1
      opt_params:
        momentum: 0.9
        weight_decay: 1e-6
      sched_name: cosine_annealing
      sched_params:
        t_mult: 1
        eta_min: 0
      warmup_params:
        use: True
        multiplier: 10.0
        warmup: 10
    semantic_params:
      modelname: resnet18
      pretrained: false
      simclr_dim: 128
      epochs: 700
      batch_size: 32
      num_workers: 8
      opt_name: SGD
      lr: 0.1
      opt_params:
        momentum: 0.9
        weight_decay: 1e-6
      sched_name: cosine_annealing
      sched_params:
        t_mult: 1
        eta_min: 0
      warmup_params:
        use: True
        multiplier: 10.0
        warmup: 10