AL:
  ood_ratio: 0.1
  nb_id_class: 4

CLIPN:
  use: true
  use_sim: false
  model_type: ViT-B-16
  ckp_path: ./checkpoints/clipn_atd-repeat3.pt
  prompt_path: ./prompt_template/prompt128.txt
  batch_size: 32
  metric_params:
    use: false
    epochs: 20
    test_ratio: 0.3
    opt_name: AdamW
    lr: 0.00001
    opt_params:
      weight_decay: 0.00005

