AL:
  strategy: EOAL
  ood_ratio: 0.1
  nb_id_class: 4
  openset_params:
    w_unk_cls: 1
    w_ent: 1.
    pareta_alpha: 0.8
    reg_w: 0.1
    train_params:
      epochs: 100
      batch_size: 32
      temperature: 0.5
    binary_clf_params:
      num_workers: 8
      opt_name: SGD
      lr: 0.1
      opt_params:
        weight_decay: 5e-4
        momentum: 0.9
      sched_name: step_lr
      sched_params:
        step_size: 20
        gamma: 0.5
    detector_params:
      modelname: resnet18
      num_workers: 8
      opt_name: SGD
      lr: 0.1
      opt_params:
        weight_decay: 5e-4
        momentum: 0.9
      sched_name: step_lr
      sched_params:
        step_size: 20
        gamma: 0.5