EXP_NAME: LearningLossAL-150epochs
SEED: 223
DATASET:
  datadir: /datasets
  dataname: CIFAR100
  img_size: 32
  num_classes: 100
  batch_size: 32
  test_batch_size: 256
  num_workers: 12
  mean:
    - 0.5071
    - 0.4867
    - 0.4408
  std:
    - 0.2675
    - 0.2565
    - 0.2761
OPTIMIZER:
  opt_name: SGD
  lr: 0.1
TRAIN:
  epochs: 150
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  use_wandb: true
MODEL:
  modelname: resnet18
  params:
    loss_weight: 1.0
    margin: 1.0
    layer_ids:
    - layer1
    - layer2
    - layer3
    - layer4
    in_features_list:
    - 64
    - 128
    - 256
    - 512
    out_features: 128
AL:
  strategy: LearningLossAL
  n_start: 1000
  n_query: 500
  n_end: 10000
  n_subset: null
RESULT:
  savedir: ./results/benchmark
