EXP_NAME: LeastConfidence
SEED: 223
DATASET:
  datadir: /datasets
  dataname: CIFAR100
  img_size: 32
  num_classes: 100
  batch_size: 32
  test_batch_size: 256
  num_workers: 12
OPTIMIZER:
  opt_name: SGD
  lr: 0.1
TRAIN:
  epochs: 50
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  use_wandb: true
MODEL:
  modelname: resnet18
AL:
  strategy: LeastConfidence
  n_start: 1000
  n_query: 500
  n_end: 10000
  n_subset: null
RESULT:
  savedir: ./results/benchmark
