DEFAULT:
  seed: 0
  savedir: ./results/batch/rotation
  exp_name: default
DATASET:
  datadir: /datasets
  dataname: SamsungAL
  batch_size: 128
  test_batch_size: 64
  num_workers: 12
  aug_info: null
OPTIMIZER:
  opt_name: SGD
  lr: 0.1
  params:
    momentum: 0.9
    weight_decay: 5e-4
TRAIN:
  epochs: 30
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  wandb:
    use: true
    entity: dsba-al-2023
    project_name: Active Learning - Benchmark (SSL)
MODEL:
  modelname: swin_base_patch4_window7_224.ms_in22k
  pretrained: true