DEFAULT:
  seed: 0
DATASET:
  datadir: /datasets
  batch_size: 32
  num_workers: 8
  aug_info:
    - RandomHorizontalFlip
    - RandomCrop:
        padding: 4
OPTIMIZER:
  name: SGD
  lr: 0.1
  params:
    momentum: 0.9
    weight_decay: 1e-6
    LARS:
      eps: 1e-8
      trust_coef: 0.001
SCHEDULER:
  name: cosine_annealing
  params:
    t_mult: 1
    eta_min: 0
  warmup_params:
    use: True
    multiplier: 10.0
    warmup: 10
TRAIN:
  epochs: 1000
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  wandb:
    use: false
    entity: null
    project_name: null
MODEL:
  name: resnet18
  pretrained: false
  params:
    simclr_dim: 128
SSL:
  method: SimCLRCSI
  params:
    sim_lambda: 1.0
    shift_trans_type: rotation