AL:
  strategy: MQNet
  ood_ratio: 0.1
  openset_params:
    selected_strategy: LearningLossAL
    meta_params:
      dim: 64
      epochs: 100
      steps_per_epoch: 100
      batch_size: 32
      num_workers: 4
      margin: 1.0
      opt_name: SGD
      lr: 0.001
    metric_params:
      modelname: resnet18
      pretrained: false
      simclr_dim: 128
      checkpoint_path: ./checkpoints