DEFAULT:
  seed: 0
  savedir: ./results/
DATASET:
  datadir: /datasets
  dataname: SamsungAL
  seed: 42
  batch_size: 128
  test_batch_size: 128
  num_workers: 12
  aug_info:
    - RandomHorizontalFlip
    - RandomVerticalFlip
    - Resize
OPTIMIZER:
  opt_name: AdamW
  lr: 0.00001
  params:
    weight_decay: 0.00001
TRAIN:
  epochs: 100
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  ckp_metric: bcr
  wandb:
    use: true
    entity: dsba-al-2023
    project_name: Active Learning - SamsungAL
MODEL:
  modelname: swin_base_patch4_window7_224.ms_in22k
  pretrained: true
AL:
  n_start: 5000
  n_query: 20
  n_end: 6000
  n_subset: null
  init:
    method: stratified_random_select