AL:
  strategy: LearningLossAL
  params: # swin_base_patch4_window7_224_in22k
    loss_weight: 1.0
    margin: 1.0
    layer_ids:
    - layers
    in_features_list:
    - 128
    - 256
    - 512
    - 1024
    out_features: 128
    in_layer: true
    channel_last: true
    