DEFAULT:
  seed: 0
  savedir: ./results/benchmark
DATASET:
  datadir: /datasets
  batch_size: 32
  test_batch_size: 2048
  num_workers: 12
  sampler_name: SubsetRandomSampler
  aug_info:
    - RandomResizedCrop
    - RandomHorizontalFlip
OPTIMIZER:
  name: SGD
  lr: 0.1
  params:
    weight_decay: 0.0005
SCHEDULER:
  name: cosine_annealing
  params:
    t_mult: 1
    eta_min: 0.00001
TRAIN:
  epochs: 100
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  wandb:
    use: false
    entity: null
    project_name: null
  params:
    metrics_off: false
LOSS:
  name: CrossEntropyLoss
MODEL:
  name: resnet18
  pretrained: false
AL:
  n_start: 100
  n_query: 100
  n_end: 2000
  n_subset: 0
  init:
    method: stratified_random_select
  continual: false