DEFAULT:
  seed: 0
  savedir: ./results/benchmark
DATASET:
  datadir: /datasets
  batch_size: 32
  test_batch_size: 2048
  num_workers: 12
  sampler_name: SubsetRandomSampler
  aug_info:
    - RandomCrop
    - RandomHorizontalFlip
OPTIMIZER:
  name: SGD
  lr: 0.1
SCHEDULER:
  name: cosine_annealing
  params:
    t_mult: 1
    eta_min: 0.00001
TRAIN:
  epochs: 50
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  wandb:
    use: true
    entity: dsba-al-2023
    project_name: Active Learning - Benchmark
  params:
    metrics_off: false
MODEL:
  name: resnet18
  pretrained: false
AL:
  n_start: 1000
  n_query: 500
  n_end: 10000
  n_subset: 0
  init:
    method: random_select
  continual: false