EXP_NAME: EntropySampling
SEED: 223
DATASET:
  datadir: /datasets
  batch_size: 128
  test_batch_size: 2048
  num_workers: 12
OPTIMIZER:
  opt_name: Adam
  lr: 0.001
TRAIN:
  epochs: 30
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  use_wandb: true
MODEL:
  modelname: resnet18
AL:
  strategy: EntropySampling
  n_start: 1000
  n_query: 500
  n_end: 40000
  n_subset: null
RESULT:
  savedir: ./results/benchmark
